package cn.daoInterface;

import cn.pojo.CourseBatch;
import cn.pojo.CourseBatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresourebatch
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    long countByExample(CourseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresourebatch
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int deleteByExample(CourseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresourebatch
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int insert(CourseBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresourebatch
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int insertSelective(CourseBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresourebatch
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    List<CourseBatch> selectByExample(CourseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresourebatch
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") CourseBatch record, @Param("example") CourseBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresourebatch
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int updateByExample(@Param("record") CourseBatch record, @Param("example") CourseBatchExample example);
}