package cn.daoInterface;

import cn.pojo.CourseResource;
import cn.pojo.CourseResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    long countByExample(CourseResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int deleteByExample(CourseResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int insert(CourseResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int insertSelective(CourseResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    List<CourseResource> selectByExample(CourseResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    CourseResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") CourseResource record, @Param("example") CourseResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int updateByExample(@Param("record") CourseResource record, @Param("example") CourseResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int updateByPrimaryKeySelective(CourseResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    int updateByPrimaryKey(CourseResource record);
}