package cn.pojo;

public class CourseResource {
    public CourseResource() {
    }

    public CourseResource(Integer id, String name1, String filename, String describe1, Integer filetype, String coverpath, Integer credit, Integer status, Integer courseinfoid) {
        this.id = id;
        this.name1 = name1;
        this.filename = filename;
        this.describe1 = describe1;
        this.filetype = filetype;
        this.coverpath = coverpath;
        this.credit = credit;
        this.status = status;
        this.courseinfoid = courseinfoid;
    }

    @Override
    public String toString() {
        return "CourseResource{" +
                "id=" + id +
                ", name1='" + name1 + '\'' +
                ", filename='" + filename + '\'' +
                ", describe1='" + describe1 + '\'' +
                ", filetype=" + filetype +
                ", coverpath='" + coverpath + '\'' +
                ", credit=" + credit +
                ", status=" + status +
                ", courseinfoid=" + courseinfoid +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseresoure.Id
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseresoure.Name1
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private String name1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseresoure.FileName
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseresoure.Describe1
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private String describe1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseresoure.FileType
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private Integer filetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseresoure.CoverPath
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private String coverpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseresoure.Credit
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private Integer credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseresoure.Status
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseresoure.CourseInfoId
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private Integer courseinfoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseresoure.Id
     *
     * @return the value of courseresoure.Id
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseresoure.Id
     *
     * @param id the value for courseresoure.Id
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseresoure.Name1
     *
     * @return the value of courseresoure.Name1
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public String getName1() {
        return name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseresoure.Name1
     *
     * @param name1 the value for courseresoure.Name1
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setName1(String name1) {
        this.name1 = name1 == null ? null : name1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseresoure.FileName
     *
     * @return the value of courseresoure.FileName
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseresoure.FileName
     *
     * @param filename the value for courseresoure.FileName
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseresoure.Describe1
     *
     * @return the value of courseresoure.Describe1
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public String getDescribe1() {
        return describe1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseresoure.Describe1
     *
     * @param describe1 the value for courseresoure.Describe1
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setDescribe1(String describe1) {
        this.describe1 = describe1 == null ? null : describe1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseresoure.FileType
     *
     * @return the value of courseresoure.FileType
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public Integer getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseresoure.FileType
     *
     * @param filetype the value for courseresoure.FileType
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setFiletype(Integer filetype) {
        this.filetype = filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseresoure.CoverPath
     *
     * @return the value of courseresoure.CoverPath
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public String getCoverpath() {
        return coverpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseresoure.CoverPath
     *
     * @param coverpath the value for courseresoure.CoverPath
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setCoverpath(String coverpath) {
        this.coverpath = coverpath == null ? null : coverpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseresoure.Credit
     *
     * @return the value of courseresoure.Credit
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseresoure.Credit
     *
     * @param credit the value for courseresoure.Credit
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseresoure.Status
     *
     * @return the value of courseresoure.Status
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseresoure.Status
     *
     * @param status the value for courseresoure.Status
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseresoure.CourseInfoId
     *
     * @return the value of courseresoure.CourseInfoId
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public Integer getCourseinfoid() {
        return courseinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseresoure.CourseInfoId
     *
     * @param courseinfoid the value for courseresoure.CourseInfoId
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setCourseinfoid(Integer courseinfoid) {
        this.courseinfoid = courseinfoid;
    }
}