package cn.pojo;

public class CourseBatch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseresourebatch.BatchId
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private Integer batchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseresourebatch.CourseResoureId
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private Integer courseresoureid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseresourebatch.BatchId
     *
     * @return the value of courseresourebatch.BatchId
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public Integer getBatchid() {
        return batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseresourebatch.BatchId
     *
     * @param batchid the value for courseresourebatch.BatchId
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setBatchid(Integer batchid) {
        this.batchid = batchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseresourebatch.CourseResoureId
     *
     * @return the value of courseresourebatch.CourseResoureId
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public Integer getCourseresoureid() {
        return courseresoureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseresourebatch.CourseResoureId
     *
     * @param courseresoureid the value for courseresourebatch.CourseResoureId
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setCourseresoureid(Integer courseresoureid) {
        this.courseresoureid = courseresoureid;
    }
}