package cn.pojo;

public class CourseInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseinfo.Id
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseinfo.Name
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseinfo.CourseCode
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    private String coursecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseinfo.Id
     *
     * @return the value of courseinfo.Id
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseinfo.Id
     *
     * @param id the value for courseinfo.Id
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseinfo.Name
     *
     * @return the value of courseinfo.Name
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseinfo.Name
     *
     * @param name the value for courseinfo.Name
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseinfo.CourseCode
     *
     * @return the value of courseinfo.CourseCode
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public String getCoursecode() {
        return coursecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseinfo.CourseCode
     *
     * @param coursecode the value for courseinfo.CourseCode
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setCoursecode(String coursecode) {
        this.coursecode = coursecode == null ? null : coursecode.trim();
    }
}