package cn.pojo;

import java.util.ArrayList;
import java.util.List;

public class CourseResourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public CourseResourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andName1IsNull() {
            addCriterion("Name1 is null");
            return (Criteria) this;
        }

        public Criteria andName1IsNotNull() {
            addCriterion("Name1 is not null");
            return (Criteria) this;
        }

        public Criteria andName1EqualTo(String value) {
            addCriterion("Name1 =", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1NotEqualTo(String value) {
            addCriterion("Name1 <>", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1GreaterThan(String value) {
            addCriterion("Name1 >", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1GreaterThanOrEqualTo(String value) {
            addCriterion("Name1 >=", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1LessThan(String value) {
            addCriterion("Name1 <", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1LessThanOrEqualTo(String value) {
            addCriterion("Name1 <=", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1Like(String value) {
            addCriterion("Name1 like", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1NotLike(String value) {
            addCriterion("Name1 not like", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1In(List<String> values) {
            addCriterion("Name1 in", values, "name1");
            return (Criteria) this;
        }

        public Criteria andName1NotIn(List<String> values) {
            addCriterion("Name1 not in", values, "name1");
            return (Criteria) this;
        }

        public Criteria andName1Between(String value1, String value2) {
            addCriterion("Name1 between", value1, value2, "name1");
            return (Criteria) this;
        }

        public Criteria andName1NotBetween(String value1, String value2) {
            addCriterion("Name1 not between", value1, value2, "name1");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNull() {
            addCriterion("FileName is null");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNotNull() {
            addCriterion("FileName is not null");
            return (Criteria) this;
        }

        public Criteria andFilenameEqualTo(String value) {
            addCriterion("FileName =", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotEqualTo(String value) {
            addCriterion("FileName <>", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThan(String value) {
            addCriterion("FileName >", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThanOrEqualTo(String value) {
            addCriterion("FileName >=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThan(String value) {
            addCriterion("FileName <", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThanOrEqualTo(String value) {
            addCriterion("FileName <=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLike(String value) {
            addCriterion("FileName like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotLike(String value) {
            addCriterion("FileName not like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameIn(List<String> values) {
            addCriterion("FileName in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotIn(List<String> values) {
            addCriterion("FileName not in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameBetween(String value1, String value2) {
            addCriterion("FileName between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotBetween(String value1, String value2) {
            addCriterion("FileName not between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andDescribe1IsNull() {
            addCriterion("Describe1 is null");
            return (Criteria) this;
        }

        public Criteria andDescribe1IsNotNull() {
            addCriterion("Describe1 is not null");
            return (Criteria) this;
        }

        public Criteria andDescribe1EqualTo(String value) {
            addCriterion("Describe1 =", value, "describe1");
            return (Criteria) this;
        }

        public Criteria andDescribe1NotEqualTo(String value) {
            addCriterion("Describe1 <>", value, "describe1");
            return (Criteria) this;
        }

        public Criteria andDescribe1GreaterThan(String value) {
            addCriterion("Describe1 >", value, "describe1");
            return (Criteria) this;
        }

        public Criteria andDescribe1GreaterThanOrEqualTo(String value) {
            addCriterion("Describe1 >=", value, "describe1");
            return (Criteria) this;
        }

        public Criteria andDescribe1LessThan(String value) {
            addCriterion("Describe1 <", value, "describe1");
            return (Criteria) this;
        }

        public Criteria andDescribe1LessThanOrEqualTo(String value) {
            addCriterion("Describe1 <=", value, "describe1");
            return (Criteria) this;
        }

        public Criteria andDescribe1Like(String value) {
            addCriterion("Describe1 like", value, "describe1");
            return (Criteria) this;
        }

        public Criteria andDescribe1NotLike(String value) {
            addCriterion("Describe1 not like", value, "describe1");
            return (Criteria) this;
        }

        public Criteria andDescribe1In(List<String> values) {
            addCriterion("Describe1 in", values, "describe1");
            return (Criteria) this;
        }

        public Criteria andDescribe1NotIn(List<String> values) {
            addCriterion("Describe1 not in", values, "describe1");
            return (Criteria) this;
        }

        public Criteria andDescribe1Between(String value1, String value2) {
            addCriterion("Describe1 between", value1, value2, "describe1");
            return (Criteria) this;
        }

        public Criteria andDescribe1NotBetween(String value1, String value2) {
            addCriterion("Describe1 not between", value1, value2, "describe1");
            return (Criteria) this;
        }

        public Criteria andFiletypeIsNull() {
            addCriterion("FileType is null");
            return (Criteria) this;
        }

        public Criteria andFiletypeIsNotNull() {
            addCriterion("FileType is not null");
            return (Criteria) this;
        }

        public Criteria andFiletypeEqualTo(Integer value) {
            addCriterion("FileType =", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeNotEqualTo(Integer value) {
            addCriterion("FileType <>", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeGreaterThan(Integer value) {
            addCriterion("FileType >", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("FileType >=", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeLessThan(Integer value) {
            addCriterion("FileType <", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeLessThanOrEqualTo(Integer value) {
            addCriterion("FileType <=", value, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeIn(List<Integer> values) {
            addCriterion("FileType in", values, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeNotIn(List<Integer> values) {
            addCriterion("FileType not in", values, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeBetween(Integer value1, Integer value2) {
            addCriterion("FileType between", value1, value2, "filetype");
            return (Criteria) this;
        }

        public Criteria andFiletypeNotBetween(Integer value1, Integer value2) {
            addCriterion("FileType not between", value1, value2, "filetype");
            return (Criteria) this;
        }

        public Criteria andCoverpathIsNull() {
            addCriterion("CoverPath is null");
            return (Criteria) this;
        }

        public Criteria andCoverpathIsNotNull() {
            addCriterion("CoverPath is not null");
            return (Criteria) this;
        }

        public Criteria andCoverpathEqualTo(String value) {
            addCriterion("CoverPath =", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathNotEqualTo(String value) {
            addCriterion("CoverPath <>", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathGreaterThan(String value) {
            addCriterion("CoverPath >", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathGreaterThanOrEqualTo(String value) {
            addCriterion("CoverPath >=", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathLessThan(String value) {
            addCriterion("CoverPath <", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathLessThanOrEqualTo(String value) {
            addCriterion("CoverPath <=", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathLike(String value) {
            addCriterion("CoverPath like", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathNotLike(String value) {
            addCriterion("CoverPath not like", value, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathIn(List<String> values) {
            addCriterion("CoverPath in", values, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathNotIn(List<String> values) {
            addCriterion("CoverPath not in", values, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathBetween(String value1, String value2) {
            addCriterion("CoverPath between", value1, value2, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCoverpathNotBetween(String value1, String value2) {
            addCriterion("CoverPath not between", value1, value2, "coverpath");
            return (Criteria) this;
        }

        public Criteria andCreditIsNull() {
            addCriterion("Credit is null");
            return (Criteria) this;
        }

        public Criteria andCreditIsNotNull() {
            addCriterion("Credit is not null");
            return (Criteria) this;
        }

        public Criteria andCreditEqualTo(Integer value) {
            addCriterion("Credit =", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditNotEqualTo(Integer value) {
            addCriterion("Credit <>", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditGreaterThan(Integer value) {
            addCriterion("Credit >", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditGreaterThanOrEqualTo(Integer value) {
            addCriterion("Credit >=", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditLessThan(Integer value) {
            addCriterion("Credit <", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditLessThanOrEqualTo(Integer value) {
            addCriterion("Credit <=", value, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditIn(List<Integer> values) {
            addCriterion("Credit in", values, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditNotIn(List<Integer> values) {
            addCriterion("Credit not in", values, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditBetween(Integer value1, Integer value2) {
            addCriterion("Credit between", value1, value2, "credit");
            return (Criteria) this;
        }

        public Criteria andCreditNotBetween(Integer value1, Integer value2) {
            addCriterion("Credit not between", value1, value2, "credit");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("Status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("Status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("Status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("Status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("Status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("Status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("Status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("Status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("Status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("Status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCourseinfoidIsNull() {
            addCriterion("CourseInfoId is null");
            return (Criteria) this;
        }

        public Criteria andCourseinfoidIsNotNull() {
            addCriterion("CourseInfoId is not null");
            return (Criteria) this;
        }

        public Criteria andCourseinfoidEqualTo(Integer value) {
            addCriterion("CourseInfoId =", value, "courseinfoid");
            return (Criteria) this;
        }

        public Criteria andCourseinfoidNotEqualTo(Integer value) {
            addCriterion("CourseInfoId <>", value, "courseinfoid");
            return (Criteria) this;
        }

        public Criteria andCourseinfoidGreaterThan(Integer value) {
            addCriterion("CourseInfoId >", value, "courseinfoid");
            return (Criteria) this;
        }

        public Criteria andCourseinfoidGreaterThanOrEqualTo(Integer value) {
            addCriterion("CourseInfoId >=", value, "courseinfoid");
            return (Criteria) this;
        }

        public Criteria andCourseinfoidLessThan(Integer value) {
            addCriterion("CourseInfoId <", value, "courseinfoid");
            return (Criteria) this;
        }

        public Criteria andCourseinfoidLessThanOrEqualTo(Integer value) {
            addCriterion("CourseInfoId <=", value, "courseinfoid");
            return (Criteria) this;
        }

        public Criteria andCourseinfoidIn(List<Integer> values) {
            addCriterion("CourseInfoId in", values, "courseinfoid");
            return (Criteria) this;
        }

        public Criteria andCourseinfoidNotIn(List<Integer> values) {
            addCriterion("CourseInfoId not in", values, "courseinfoid");
            return (Criteria) this;
        }

        public Criteria andCourseinfoidBetween(Integer value1, Integer value2) {
            addCriterion("CourseInfoId between", value1, value2, "courseinfoid");
            return (Criteria) this;
        }

        public Criteria andCourseinfoidNotBetween(Integer value1, Integer value2) {
            addCriterion("CourseInfoId not between", value1, value2, "courseinfoid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table courseresoure
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 01 18:52:52 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table courseresoure
     *
     * @mbg.generated Thu Aug 01 18:52:52 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}